////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 David Košenina
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __OsciloskopThermal__
#define __OsciloskopThermal__

/**
@file
Subclass of Thermal, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Thermal */
class OsciloskopThermal : public Thermal
{
	protected:
		// Handlers for Thermal events.
		void ThermalOnActivate( wxActivateEvent& event );
		void m_textCtrlHeatingOnTextEnter( wxCommandEvent& event );
		void m_sliderHeatOnScroll( wxScrollEvent& event );
		void m_textCtrlCoolingOnTextEnter( wxCommandEvent& event );
		void m_sliderCoolOnScroll( wxScrollEvent& event );
		void m_checkBoxEnabledOnCheckBox( wxCommandEvent& event );
		void m_buttonOkOnButtonClick( wxCommandEvent& event );
		void m_buttonDefaultOnButtonClick( wxCommandEvent& event );
		void m_buttonCancelOnButtonClick( wxCommandEvent& event );
      void m_spinBtnHeatingOnSpinUp(wxSpinEvent& event);
      void m_spinBtnHeatingOnSpinDown(wxSpinEvent& event);
      void m_spinBtnCoolingOnSpinUp(wxSpinEvent& event);
      void m_spinBtnCoolingOnSpinDown(wxSpinEvent& event);
	public:
		/** Constructor */
		OsciloskopThermal( wxWindow* parent );
	//// end generated class members

};

#endif // __OsciloskopThermal__
