////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 David Košenina
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __OsciloskopInfo__
#define __OsciloskopInfo__

/**
@file
Subclass of Info, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Info */
class OsciloskopInfo : public Info
{
	protected:
		// Handlers for Info events.
		void ThermalOnActivate( wxActivateEvent& event );
		void InfoOnClose( wxCloseEvent& event );
		void m_textCtrlLicenseOnTextURL( wxTextUrlEvent& event );
		void m_textCtrlGlewOnTextURL( wxTextUrlEvent& event );
		void m_textCtrlInfoOnTextURL( wxTextUrlEvent& event );
		void m_textCtrlDocumentationOnTextURL( wxTextUrlEvent& event );
		void m_buttonOkOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		OsciloskopInfo( wxWindow* parent );
	//// end generated class members
	
};

#endif // __OsciloskopInfo__
