////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 David Košenina
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __OsciloskopHardwareGenerator__
#define __OsciloskopHardwareGenerator__

/**
@file
Subclass of HardwareGenerator, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing HardwareGenerator */
class OsciloskopHardwareGenerator : public HardwareGenerator
{
	protected:
		// Handlers for HardwareGenerator events.
		void HardwareGeneratorOnInitDialog( wxInitDialogEvent& event );
		void m_comboBoxTypeOnCombobox( wxCommandEvent& event );
		void m_textCtrlFrequencyOnTextEnter( wxCommandEvent& event );
		void m_textCtrlVoltage0OnTextEnter( wxCommandEvent& event );
		void m_sliderVoltageOnScroll( wxScrollEvent& event );
		void m_textCtrlOffset0OnTextEnter( wxCommandEvent& event );
		void m_sliderOffsetOnScroll( wxScrollEvent& event );
		void m_textCtrlSquareDuty0OnTextEnter( wxCommandEvent& event );
		void m_sliderSquareDutyOnScroll( wxScrollEvent& event );
		void m_checkBoxSawSlopeOnCheckBox( wxCommandEvent& event );
		void m_filePicker1OnFileChanged( wxFileDirPickerEvent& event );
		void m_buttonCustomFileOnButtonClick( wxCommandEvent& event );
		void m_radioBtnOnOnRadioButton( wxCommandEvent& event );
		void m_radioBtnOffOnRadioButton( wxCommandEvent& event );
		void m_comboBoxType1OnChoice( wxCommandEvent& event );
		void m_textCtrlFrequency1OnTextEnter( wxCommandEvent& event );
		void m_textCtrlVoltage1OnTextEnter( wxCommandEvent& event );
		void m_sliderVoltage1OnScroll( wxScrollEvent& event );
		void m_textCtrlOffset1OnTextEnter( wxCommandEvent& event );
		void m_sliderOffset1OnScroll( wxScrollEvent& event );
		void m_textCtrlSquareDuty1OnTextEnter( wxCommandEvent& event );
		void m_sliderSquareDuty1OnScroll( wxScrollEvent& event );
		void m_checkBoxSawSlope1OnCheckBox( wxCommandEvent& event );
		void m_filePicker11OnFileChanged( wxFileDirPickerEvent& event );
		void m_buttonCustomFile1OnButtonClick( wxCommandEvent& event );
		void m_radioBtnOn1OnRadioButton( wxCommandEvent& event );
		void m_radioBtnOff1OnRadioButton( wxCommandEvent& event );
		void m_buttonOkOnButtonClick( wxCommandEvent& event );
		void m_buttonDefaultOnButtonClick( wxCommandEvent& event );
		void m_buttonCancelOnButtonClick( wxCommandEvent& event );
      void m_spinBtnCh0VoltOnSpinUp(wxSpinEvent& event);
      void m_spinBtnCh0VoltOnSpinDown(wxSpinEvent& event);
      void m_spinBtnCh0OffsetOnSpinUp(wxSpinEvent& event);
      void m_spinBtnCh0OffsetOnSpinDown(wxSpinEvent& event);
      void m_spinBtnCh1VoltOnSpinUp(wxSpinEvent& event);
      void m_spinBtnCh1VoltOnSpinDown(wxSpinEvent& event);
      void m_spinBtnCh1OffsetOnSpinUp(wxSpinEvent& event);
      void m_spinBtnCh1OffsetOnSpinDown(wxSpinEvent& event);
      void m_spinBtnGen0SqrDutyOnSpinUp(wxSpinEvent& event);
      void m_spinBtnGen0SqrDutyOnSpinDown(wxSpinEvent& event);
      void m_spinBtnGen1SqrDutyOnSpinUp(wxSpinEvent& event);
      void m_spinBtnGen1SqrDutyOnSpinDown(wxSpinEvent& event);
	public:
		/** Constructor */
		OsciloskopHardwareGenerator( wxWindow* parent );
	//// end generated class members
	
};

#endif // __OsciloskopHardwareGenerator__
